# Generated by Django 5.2.1 on 2025-06-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('datetime', models.DateTimeField(verbose_name='Дата/Время')),
                ('is_ok', models.BooleanField(default=False, verbose_name='Статус отправки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор Телеграм')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Юзернейм')),
                ('first_name', models.CharField(blank=True, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, null=True, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ')], verbose_name='Тип вложения')),
                ('file', models.FileField(upload_to='media/mailing', verbose_name='Файл')),
                ('file_id', models.TextField(null=True)),
                ('mailing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='panel.mailing')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
